### ISSUE TITLE
esp32 FreeRTOS

### ISSUE THREAD

**Issue by garfy0886** [nats-io/nats.c#197]
We need to integrate NATS on FreeRTOS (esp32 processor). 
Is it possible? What changes are required in Makefile in order to build the libraries for the FreeRTOS O.S.

Thank you in advance.
Best

**Comment by kozlovic** [comment]
I have no idea and not the bandwidth right now to look into that. What would one require to setup an environment to be able to test that?

**Comment by koper89** [comment]
@garfy0886 Did you succeed in it? I'm about to try something similar.

**Comment by Al3x4n** [comment]
interested

**Comment by kozlovic** [comment]
At this point, I am going to close this issue because I have no idea how to even check this, but my guess is that it would either not work or require drastic changes to the library in order to be able to work on this OS. 
From wikipedia:
```
There are none of the more advanced features typically found in operating systems like Linux or Microsoft Windows, such as device drivers, advanced memory management, user accounts, and networking.
```
NATS being a messaging system, the "none of advanced features... networking" mention is not promising.

**Comment by luan007** [comment]
FYI

ESP32 related:
https://github.com/martin-ger/esp32_nat_router

Embedded Env (Arduino):
https://github.com/isobit/arduino-nats
https://github.com/davidsai/arduino-nats-streaming-client
