### ISSUE TITLE
C++ nats freeze in natsConn_bufferFlush method (system call "send")

### ISSUE THREAD

**Issue by yuashuplyak** [nats-io/nats.c#272]
Hello!

I have a problem with nats-c 1.8.0 for c++.
Data is read from a lot of number of tty-devices in different threads and sent by nats (nats-c 1.8.0) (180 message/sec).
Application seldom receive a SIGPIPE-signal, then data is't sent, and application continues to work.

Another option is to nats freeze in natsConn_bufferFlush method (system call "send"), holding the mutex. This leads the program to freeze completely.

What could be the problem?

![stack](https://user-images.githubusercontent.com/25077638/66308218-98e25480-e917-11e9-96a1-669ee390a99d.png)

**Comment by kozlovic** [comment]
> Application seldom receive a SIGPIPE-signal, then data is't sent, and application continues to work.

The library is setting a signal handler for SIGPIPE and ignores it, so that should not cause any problem to the library: https://github.com/nats-io/nats.c/blob/master/src/nats.c#L965

> Another option is to nats freeze in natsConn_bufferFlush method (system call "send"), holding the mutex. This leads the program to freeze completely.

We have added the option to set write deadline in the latest release v2.1.0 (https://github.com/nats-io/nats.c/releases/tag/v2.1.0) that could help in situations where a socket write would block due to many reasons such as the other side not dequeuing data fast enough or the TCP connection being in a bad state but not reported as closed.

**Comment by yuashuplyak** [comment]
Thank you for answer.

> The library is setting a signal handler for SIGPIPE and ignores it, so that should not cause any problem to the library: https://github.com/nats-io/nats.c/blob/master/src/nats.c#L965

Yes, I saw it.
But after gdb catch the SIGPIPE signal, the connection drops and is not restored.

Ok. I will try version v2.1.0.
I will inform you about the results

**Comment by kozlovic** [comment]
> But after gdb catch the SIGPIPE signal, the connection drops and is not restored.

Yes, but if you run in GDB there is a lot of things that won't work as expected since timers are stopped while you debug, etc..

**Comment by yuashuplyak** [comment]
Unfortunately, the problem is not resolved.
Using the new version did not help.
Sending Data interrupted when increases the load on the network (nats server).

The behavior of the program remains the same:
1. program freezes;
2. program doesn't freeze, but data isn't sent.

More often this is the second option.

Nats server version is upgrade to 2.1.

**Comment by kozlovic** [comment]
The v2.1.0 I was talking about is for the NATS C client that introduces the natsOptions_SetWriteDeadline() option (to make a tcp write call timeout if call would block).

**Comment by yuashuplyak** [comment]
#define NATS_VERSION_STRING "2.1.0"

**Comment by yuashuplyak** [comment]
client and server were upgrade.

**Comment by kozlovic** [comment]
I posted this because you wrote: `Nats server version is upgrade to 2.1.`.
Have you set the write deadline option to all your connections?

**Comment by kozlovic** [comment]
Note that you can set it through environment variable so that you don't have to manually set it on all your connections:
```
NATS_DEFAULT_LIB_WRITE_DEADLINE=2000
```
would set the default write deadline to 2 seconds.

**Comment by yuashuplyak** [comment]
I'm sorry. No. I will try. Do you recommend 2 second?

**Comment by kozlovic** [comment]
I can't recommend any value, it is really up to your tolerance of how long you want to allow a TCP write to block. Keep in mind that if a write blocks, with this option connection will be closed, which may trigger a reconnect, but still.
And I am not saying that this is for sure the solution to your problem, but I asked you to try that if you say that you see your application being stuck in a send() call.

**Comment by yuashuplyak** [comment]
OK. Thank you.

**Comment by kozlovic** [comment]
@yuashuplyak And again, going back to original description, the library sets SIG_IGN for the SIGPIPE handler, so that signal should not surface, if it does, please let me know what you did for that to happen. Did you setup your own handler and disabled NATS C client's one somehow?
In GDB, if you don't want GDB to stop at SIGPIPE, do this in GDB prompt:
```
handle SIGPIPE nostop noprint pass
```

**Comment by yuashuplyak** [comment]
"... after gdb catch the SIGPIPE signal, the connection drops and is not restored." (program start in debug mode, example: gdb program ... )
I don't think this is a coincidence.

I'm not an expert.
I read that SIGPIPE ignoring is general practical.  But this signal is a disconnect symptom.
Have maybe to make SIGPIPE signal handler, that will reconnect to the nats-server?

I will write after a test of the NATS_DEFAULT_LIB_WRITE_DEADLINE parameter.
Maybe it will solve the problem.

**Comment by kozlovic** [comment]
Again, NATS C library does set a signal handler for SIGPIPE and set it to SIG_IGN. You don't want the process to exit simply because a connection has been closed. By ignoring this signal, it allows the application to check when a tcp write fails and handles this cleanly as opposed to simply having the process exit.

**Comment by kozlovic** [comment]
> Have maybe to make SIGPIPE signal handler, that will reconnect to the nats-server?

No you don't. The library set this handler to SIG_IGN and handles reconnect on its own. Something is really strange in your application if you have such issues.

**Comment by rigtorp** [comment]
@kozlovic It's better to use `MSG_NOSIGNAL`, this way nats.c doesn't have to mess with signals for the whole program.

**Comment by kozlovic** [comment]
PR https://github.com/nats-io/nats.c/pull/277 implemented the MSG_NOSIGNAL and SO_NOSIGPIPE. It is available in the main branch but not in official release yet. Closing this for now, it can be re-opened if need be.
