### ISSUE TITLE
What is the reason to use volatile modifier?

### ISSUE THREAD

**Issue by tshev** [nats-io/nats.c#274]
https://github.com/nats-io/nats.c/blob/2320bcb9d2decac1af06d71176e77f37fc12122f/examples/examples.h#L41

**Comment by kozlovic** [comment]
This is because this variable is (incorrectly) checked without locking in the examples in different threads (https://github.com/nats-io/nats.c/blob/master/examples/subscriber.c#L33). In production code you would use locking to protect this variable.
The `volatile` keyword will prevent compiler to do some optimizations that would break the code. It forces the loading of the variable when accessed.

**Comment by tshev** [comment]
Thank you. I was a little bit worried because I was expecting to see something similar inside of the library. Now I can sleep better.
