### ISSUE TITLE
NATS message headers

### ISSUE THREAD

**Issue by arajitsamanta** [nats-io/nats.c#279]
I am trying to figure out following with NATS Server(Without Streaming)

- In Request/Reply messaging pattern how do I make sure subscriber "acknowledge" a message ?
Looking at https://nats-io.github.io/docs/developer/concepts/acks.html it seems it doable. however it talks about sending a message with "No payload". Does that mean publisher need to perform two step process for each message(one without payload to get ACK and another with actual payload) ?

- Looking at the NATS documentation I cant seem to have a complete understanding if NATS support message headers(Like MQMD headers in IBM MQ series) . Reason i am looking to pass header is to have a way to pass contextual information like UUID, message type(like PROBE/HEARTBEAT/REQUEST etc) in headers instead of payload.

Any suggestion would be helpful.

**Comment by kozlovic** [comment]
> In Request/Reply messaging pattern how do I make sure subscriber "acknowledge" a message ?
Looking at https://nats-io.github.io/docs/developer/concepts/acks.html it seems it doable. however it talks about sending a message with "No payload". Does that mean publisher need to perform two step process for each message(one without payload to get ACK and another with actual payload) ?

If you want to make sure that the producer knows if an application has processed the message at least once, you could have the producer send a request and wait for a reply (the Request() call does that for you) instead of simply publishing the message. The application that receives the request can respond to let the producer know that the message has been processed. The doc simply says that this response could be an empty message. There is no requirement here from NATS messaging perspective. This is purely application logic acknowledgement.

> Looking at the NATS documentation I cant seem to have a complete understanding if NATS support message headers(Like MQMD headers in IBM MQ series) . Reason i am looking to pass header is to have a way to pass contextual information like UUID, message type(like PROBE/HEARTBEAT/REQUEST etc) in headers instead of payload.

NATS does not have headers indeed. You would need to have the payload contain this information.
