### ISSUE TITLE
Receive Message as Byte array or char *

### ISSUE THREAD

**Issue by Qhodok** [nats-io/nats.c#289]
how to receive a char * message on NATS stream?

**Comment by kozlovic** [comment]
As indicated [here](https://nats-io.github.io/nats.c/group__stan_msg_group.html#ga2cee54b6bfadf5b82a95caf75bfaf7d8), the library adds internally a NULL character at the end of the message payload, so that if user expects the content to be a string, they can conveniently call `stanMsg_GetData()` without having to copy the returned data to a buffer to add the NULL byte at the end.
