### ISSUE TITLE
nats.c disconnectedCb and discoveredServers callbacks problem

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#321]
Hello. I've added all nats.c callbacks to my library and wrote some tests for them. I've found some behaviour that I could not explain with callbacks mentioned in the topic:

1) Regarding disconnectedCb documentation says:

> There could be two instances of the callback when reconnection is allowed: one before attempting the reconnect attempts, and one when all reconnect attempts have failed and the connection is going to be permanently closed.

I have a test that sets reconnect attempts to 1, launches one-node cluster and connects client to it. Then cluster is stopped, and I can see, that my disconnectedCb is called but only once (even after I've added 1 second sleep after cluster stop to be sure that dispatched callbacks are called). Then closedCb is called, but I never get second disconnectedCb call. Documentation says that second call **could** take place but looks like it is not guaranteed. Can you please explain, whether observed behaviour is ok in my case?

2) For discoveredServersCb I have a test, that launches 2-node cluster and configures client with only one url. Then client is connected and for a short period of time natsConnection_GetDiscoveredServers returns only one url, then it starts returning url of second node also. But my discoveredServersCb never gets called (also tried to add a 1 second timeout to be sure dispatched callback is actually called). What can be the reason?

**Comment by kozlovic** [comment]
> Documentation says that second call could take place but looks like it is not guaranteed. Can you please explain, whether observed behaviour is ok in my case?

This is a documentation error. The problem has been fixed long ago (back in v1.2.10). I will fix the doc.

> For discoveredServersCb I have a test, that launches 2-node cluster and configures client with only one url. (...) But my discoveredServersCb never gets called (also tried to add a 1 second timeout to be sure dispatched callback is actually called). What can be the reason?

The callback is invoked only after the initial connect. This means that if you had only 1 server running and connect your app, then start the second server that routes to the first one, this callback would be invoked.
The reason is rather technical: if server(s) are discovered while the initial connect, the connection object is technically not fully created yet (not returned to the user), so having a connection that is not fully created as part of the argument of the discovered callback seemed risky.
