### ISSUE TITLE
Problem with indefinite reconnect

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#325]
Hello. I've asked you a question some time ago about slow consumers and the reason nats client can be disconnected from server. You gave an advice to set errorHandler cb. I've also added all other available callbacks for disconnect/reconnect/close events. Tonight the bug was catched again, may be you can give advice where to look for solution? My production environment is the following:
1) 3 node nats cluster using token authorization
2) basic client settings: libuv-based, very large number of reconnect attempts set, small (50ms) reconnect interval, small io buffer size (32KB), creates 1 subscription only, does not publish anything
3) after inspecting nats server statistics I'm pretty sure, that initial disconnect occurred because client was marked as slow consumer by nats server (time of two events are the same). No errorHandler callback was called (no messages was lost in the client itself)
4) Then client starts to reconnect. In my logs I can see how reconnect callback is called and shortly after - disconnectCb. I'm also checking last error on nats connection (with getLastError) in disconnectCb and it always equal NATS_OK.
5) In servers connz statistics I have a lot of records like this:
```
  "connections": [
    {
      "cid": 33330,
      "ip": "10.0.0.159",
      "port": 60843,
      "start": "2020-05-26T17:06:30.268746315Z",
      "last_activity": "2020-05-26T17:06:30.287896956Z",
      "stop": "2020-05-26T17:06:30.298093097Z",
      "reason": "Client Closed",
      "rtt": "1.275158ms",
      "uptime": "0s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 1,
      "name": "GCM_CLIENT.a",
      "lang": "C",
      "version": "2.1.0"
    },
```
Note that even subscription is created (at least it is mentioned in stats), but then connection is closed. My app stops client only on exit (calling natsConnection_Close or Drain), and it continues to work all the time (ignoring missing connection to nats server). Is there any other reason (except explicit connection close) that can lead to "Client Closed" reason in nats server statistics? 

6. When connection is finally closed, closedCb is called and getLastError returns 6 (NATS_NO_SERVER) inside it (but all nats servers are running: other clients are fine, servers can answer on statistics requests). I do not understand why reconnect attempts were stopped after about 30 minutes (only about 35000 took place while I set number of them to MAX_INT), maybe OS reacted somehow..

Not very important for me why reconnect attempts were stopped (I suppose that it's because of my environment). But I can't find out a reason for described reconnect behaviour.. Will be grateful for any advices.

**Comment by kozlovic** [comment]
If connection was closed by server you should see it in log file and with monitoring endpoint `/connz?state=closed`, assuming that you did you have too many closed connections since server uses a ring buffer of 1000 closed connections:
```
"connections": [
    {
      "cid": 1,
      "ip": "127.0.0.1",
      "port": 63298,
      "start": "2020-05-26T13:05:45.08071-06:00",
      "last_activity": "2020-05-26T13:06:04.353385-06:00",
      "stop": "2020-05-26T13:06:06.354097-06:00",
      "reason": "Slow Consumer (Write Deadline)",
      "rtt": "201µs",
      "uptime": "21s",
      "idle": "2s",
      "pending_bytes": 66555,
      "in_msgs": 0,
      "out_msgs": 4158,
      "in_bytes": 0,
      "out_bytes": 532224,
      "subscriptions": 1,
      "name": "NATS Sample Subscriber",
      "lang": "go",
      "version": "1.9.2"
    },
```

> Then client starts to reconnect. In my logs I can see how reconnect callback is called and shortly after - disconnectCb.

That already is not normal. Meaning that for a given connection, the disconnectCb will be invoked before the reconnectCb. Meaning that the library will let you know that the library was disconnected, then, if there is a successful reconnect, the reconnectCb will fire. Now, as explained before, those callbacks are serialized but not invoked in place, so the current state of the connection may not match what those callback indicate: that is, a disconnectedCb may fire but the connection already be reconnected.

> Note that even subscription is created (at least it is mentioned in stats), but then connection is closed.

But in the output you see that the start time and last activity/stop is few millisecond apart. And this connection is reported as closed. So not sure what's going on here if you really don't close the connection.

**Comment by pananton** [comment]
Yes, disconnectCb invoked before reconnectCb, just not mentioned that first disconnect, sorry. If you do not see other problems will continue to search, probably make some test build with more log output, thanks!

**Comment by kozlovic** [comment]
@pananton I know that you have been dealing with slow consumers (in the client). Another user just reported an issue with the library not properly invoking the error handler in first trigger of a slow consumer (again, talking about messages dropped because subscription's pending limit reached). See #328.

**Comment by pananton** [comment]
Thank's @kozlovic . I've upgraded my code to new master. I will write here whether this helped.

**Comment by kozlovic** [comment]
@pananton Any update? I am closing this now and will re-open if you still have issues.
