### ISSUE TITLE
Manual request management

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#335]
Hello @kozlovic . I'm using requests in my code but the easiest function natsConnection_Request does not suite me well because it blocks while waiting for reply. I've decided to use another logic:
1. use natsInbox_Create to create unique inbox for reply
2. use natsConnection_SubscribeTimeout to asynchronously subscribe to inbox and set timeout for my requests
3. use natsSubscription_AutoUnsubscribe and set it to 1 (to accept only one reply)
4. use natsConnection_PublishRequest with my inbox

Am I doing it right? Does not this code introduce any overload to client or server? I think, that simple natsConnection_Request works the same way under the cover, so no performance drop should occur - is it correct? Does natsConnection_PublishRequest  sends data asap even if natsOptions specify the opposite (i.e. sendAsap is false)?

**Comment by kozlovic** [comment]
> Am I doing it right? Does not this code introduce any overload to client or server?

Kind of. The Request() API does not create a subscription for each request (except if running with the old style request). What the library does is create a wildcard subscription per connection for requests. A unique token is added to the connection's request's root so that each request is still unique, but the reply will be received through that internal subscription.

You could achieve the same though, but it means that this subscription is long lived and you then need to match the reply with the request, similar to what the library do.

But again, depending on the volume of requests, it may be ok to do it the way you describe.

**Comment by pananton** [comment]
Yeah, I will implement in your way - I did not like the idea to create new subscription for each request. Thanks. But what about natsConnection_PublishRequest  and its relation to sendAsap ? Will data published with this method sent immediately even if sendAsap is not enabled?

**Comment by kozlovic** [comment]
@pananton No it won't be sent immediately. You would need to set the option. The reason is that in contrast to Request() where this call blocks and waits for the reply in place, it is better to send the request right away. But natsConnection_PublishRequest() "does not block", so users may call many of different publish or other calls and may not want the data to be sent right away (reducing overall throughput).

**Comment by pananton** [comment]
Ok, thanks for answers!
