### ISSUE TITLE
No reconnecting after first failed connect attempt (in combination with libevent)

### ISSUE THREAD

**Issue by kingkorf** [nats-io/nats.c#341]
Hi, I'm using this library in combination with libevent but reconnecting after first failed connect attempt as described in the documentation (natsOptions_SetMaxReconnect, natsOptions_SetReconnectWait) does not seem to work. I've used examples/libevent-sub.c as a basis and removed the check on 's' to start the event loop whether the first connection is NATS_OK or not. 

The first attempt fails when the machine this runs on first boots and the software starts from the inittab and has no networking available yet. It's a simple machine/os with busybox and I have no option to wait for networking.

Here is a snippet from the code:

```
    if (s == NATS_OK)
    {
        s = natsOptions_SetMaxReconnect(opts, -1);

        if (s != NATS_OK)
        {
            syslog(LOG_ERR, "Can't set NATS max. reconnect");
        }
    }

    if (s == NATS_OK)
    {
        int reconnectWait = (rand() % (20000 - 1000)) + 1000;
        s = natsOptions_SetReconnectWait(opts, reconnectWait);

        if (s != NATS_OK)
        {
            syslog(LOG_ERR, "Can't set NATS reconnect wait (%d)", reconnectWait);
        }
    }

    if (s == NATS_OK)
    {
        s = natsOptions_SetRetryOnFailedConnect(opts, true, connectedCB, NULL);

        if (s != NATS_OK)
        {
            syslog(LOG_ERR, "Can't set NATS retry options");
        }
    }

    if (s == NATS_OK)
    {
        s = natsOptions_SetTimeout(opts, 10000);

        if (s != NATS_OK)
            syslog(LOG_ERR, "Can't set NATS timeout");
    }

    if (s == NATS_OK)
    {
        s = natsOptions_SetSendAsap(opts, 1);

        if (s != NATS_OK)
            syslog(LOG_ERR, "Can't set NATS 'send asap' option");
    }

    natsLibevent_Init();

    evLoop = event_base_new();
    if (evLoop == NULL)
    {
        s = NATS_ERR;
    }

    if (s == NATS_OK)
    {
        s = natsOptions_SetEventLoop(opts, (void *)evLoop,
                                     natsLibevent_Attach,
                                     natsLibevent_Read,
                                     natsLibevent_Write,
                                     natsLibevent_Detach);

        if (s != NATS_OK)
        {
            syslog(LOG_ERR, "Can't attach event loop");
        }
    }

    if (s == NATS_OK)
    {
        s = natsConnection_Connect(&conn, opts);
        syslog(LOG_INFO, "NATS connect returned: %s", natsStatus_GetText(s));

        if (s != NATS_OK)
        {
            syslog(LOG_ERR, "Can't connect to NATS servers (%d)", s);
        }
    }

    /** here are some events attached **/

    event_base_dispatch(evLoop);
```

It gives the following output:

```
<14>Jul  2 09:49:07 box-client[953]: NATS connect returned: Not Yet Connected
<11>Jul  2 09:49:07 box-client[953]: Can't connect to NATS servers (31)
```

After that nothing else seems to happen. Am I missing something?

**Comment by kozlovic** [comment]
First you need to ensure that the event loop has something to dispatch and does not directly exit because there are not active file descriptors. I assume this is what you mean with "/** here are some events attached **/".
From up-to-date master, following is a patch of libuvent-sub.c with some changes that work for me. The idea is that I start a server on port 4223 and create a second connection that connects to this running server. This connection is added to the event loop so I am sure that event_base_dispatch has some work to do.

I have changed your reconnectWait setting to be simply 1000 (1sec) otherwise it may take a bit long for the reconnect to happen (since the first time I used you code, the reconnecWait was more than 8sec).
I start the test and it connects to 4223 but can't connect to 4222, and reports so.
Then later I start a server on port 4222, and I can see the message CONNECTED!!! being printed. As a verification that everything else works, I then start a `nats-publisher` that sends the expected number of messages and see that the connection that was using natsOptions_SetRetryOnFailedConnect() has now received all messages and exit.

So here is the patch:
```
diff --git a/examples/libevent-sub.c b/examples/libevent-sub.c
index 5b9677a..8e4bb7d 100644
--- a/examples/libevent-sub.c
+++ b/examples/libevent-sub.c
@@ -39,14 +39,23 @@ onMsg(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure)
     {
         elapsed = nats_Now() - start;
 
+        natsConnection_Close((natsConnection*) closure);
         natsConnection_Close(nc);
     }
 }
 
+static void
+connectedCB(natsConnection  *nc, void *closure)
+{
+    printf("@@IK: CONNECTED!!!!\n");
+}
+
 int main(int argc, char **argv)
 {
     natsConnection      *conn  = NULL;
+    natsConnection      *conn2 = NULL;
     natsOptions         *opts  = NULL;
+    natsOptions         *opts2 = NULL;
     natsSubscription    *sub   = NULL;
     natsStatus          s      = NATS_OK;
     struct event_base   *evLoop= NULL;
@@ -65,6 +74,19 @@ int main(int argc, char **argv)
     if (evLoop == NULL)
         s = NATS_ERR;
 
+    if (s == NATS_OK)
+        s = natsOptions_Create(&opts2);
+    if (s == NATS_OK)
+        s = natsOptions_SetURL(opts2, "nats://127.0.0.1:4223");
+    if (s == NATS_OK)
+        s = natsOptions_SetEventLoop(opts2, (void*) evLoop,
+                                     natsLibevent_Attach,
+                                     natsLibevent_Read,
+                                     natsLibevent_Write,
+                                     natsLibevent_Detach);
+    if (s == NATS_OK)
+        s = natsConnection_Connect(&conn2, opts2);
+
     // Indicate which loop and callbacks to use once connected.
     if (s == NATS_OK)
         s = natsOptions_SetEventLoop(opts, (void*) evLoop,
@@ -74,10 +96,34 @@ int main(int argc, char **argv)
                                      natsLibevent_Detach);
 
     if (s == NATS_OK)
+        s = natsOptions_SetMaxReconnect(opts, -1);
+
+    if (s == NATS_OK)
+    {
+        int reconnectWait = 1000; //(rand() % (20000 - 1000)) + 1000;
+        printf("@@IK: reconnectWait: %d\n", reconnectWait);
+        s = natsOptions_SetReconnectWait(opts, reconnectWait);
+    }
+
+    if (s == NATS_OK)
+        s = natsOptions_SetRetryOnFailedConnect(opts, true, connectedCB, NULL);
+
+    if (s == NATS_OK)
+        s = natsOptions_SetTimeout(opts, 10000);
+    
+    if ( s== NATS_OK)
+        s = natsOptions_SetSendAsap(opts, 1);
+
+    if (s == NATS_OK)
+    {
         s = natsConnection_Connect(&conn, opts);
+        printf("@@IK: Connect returned: %s (%d)\n", natsStatus_GetText(s), s);
+        if (s == NATS_NOT_YET_CONNECTED)
+            s = NATS_OK;
+    }
 
     if (s == NATS_OK)
-        s = natsConnection_Subscribe(&sub, conn, subj, onMsg, NULL);
+        s = natsConnection_Subscribe(&sub, conn, subj, onMsg, (void*)conn2);
 
     // For maximum performance, set no limit on the number of pending messages.
     if (s == NATS_OK)
@@ -102,7 +148,9 @@ int main(int argc, char **argv)
     // Destroy all our objects to avoid report of memory leak
     natsSubscription_Destroy(sub);
     natsConnection_Destroy(conn);
+    natsConnection_Destroy(conn2);
     natsOptions_Destroy(opts);
+    natsOptions_Destroy(opts2);
 
     if (evLoop != NULL)
         event_base_free(evLoop);
```
Here is the output of the run:
```
iMacSynadia:build ivan$ examples/nats-libevent-sub 
Listening on 'foo'.
@@IK: reconnectWait: 1000
@@IK: Connect returned: Not Yet Connected (31)
```
At this point I start a server on 4222:
```
@@IK: CONNECTED!!!!
```
Then from another shell start the publisher: `examples/nats-publisher`
```

Received 1000000 messages in 413 milliseconds (2421307 msgs/sec)
```

Note: With event loops, I would recommend not using `natsOptions_SetSendAsap()` because it does not make sense. With an event loop, the NATS library does not send directly, the event loop does. So any action that adds data to the buffer is flushed out by the next event loop run. Also remember that with event loops, you cannot use any NATS C API that is blocking, that is, sends something and expect data back in place, such as Request().

Hope this helps.

**Comment by kingkorf** [comment]
Thanks for the quick reply Ivan. The problem lied in the fact that my software started (from inittab) before a valid nameserver was set, so my cluster could not be resolved and apparently this locks this library in combination with libevent. Maybe you can look into this, I resolved the issue by adding two fast nameservers to resolv.conf in the /etc/rc. 

What should happen (in any software for that matter) when the software is started with an invalid nameserver in resolv.conf which later is set to a valid one?

**Comment by kozlovic** [comment]
If you provide a hostname in the URL that requires hostname resolution, then your application cannot work if it tries to create a TCP connection.

I have experimented on macOS and having the resolv.conf empty in my case was not a problem. But I changed /etc/hosts to comment out the "localhost" resolution (to 127.0.0.1/::1) and I can see that getaddrinfo() that NATS C client library invokes when trying to create a connection fails. When I put back the resolution and save the file, I can see at the next connect attempt that the resolution works and the client can connect. Clearly NATS C client does not do any caching, that is, tries to resolve for each attempt to create a TCP connection, so that should not be a problem for NATS itself.

Not sure what other events you have attached to the event loop and if that is a problem or not, but again, my experiment with non resolvable hostname on connect is not an issue as long as the hostname does become resolvable at one point the client will be able to create a NATS connection. Again, make sure that your reconnect attempts/wait are not causing you to think that nothing is happening: the create connection attempts will occur based on natsOptions_SetMaxReconnect() and pause in between for the amount of time specified with natsOptions_SetReconnectWait().
