### ISSUE TITLE
natsConnection_FlushTimeout overflow issue

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#345]
Hello @kozlovic . Found a small bug related to mentioned above function. In my library I use configuration variable flushTimeout and treat zero as +inf : make flushTimeout equal to largest possible value of int64_t (a type to represent timeout in natsConnection_FlushTimeout). If such value is passed to natsConnection_FlushTimeout then it will fail from time to time with NATS_TIMEOUT error code. I've looked a little to nats.c sources and believe that this occur because of integer overflow. I'm not sure whether something should be done with this, but want to you to know about this issue.

**Comment by kozlovic** [comment]
The given timeout is added to current time so that we do a condition variable timed wait with the target time. So if you pass the max int64_t it will always overflow. So I would expect that you would always get a timeout. We could try to cap the "now+timeout" to positive number.
But backing up a little, I am not sure you need such a big timeout. If you flush the connection (which means the library sends a PING and wait for the corresponding PONG), if it has to wait more than a few seconds, I would say the NATS Server is clearly overloaded. If the library gets disconnected, and therefore the PING possibly lost, the library fails any pending Flush.
So again, I would limit the flush timeout to a much lower value. The existence of FlushTimeout() was actually for people needing less than the default timeout used in Flush() (which used to be 60s, but is now 10s).

**Comment by pananton** [comment]
It's strange but I always get timeout when build with gcc and never when build with msvc (both are 64 bit)..
Regarding large timeout. I use 0 in my config as a value which tells my client to wait indefinite. Because nats.c does not treat 0 as some special value, I convert it internally to very large timeout - and max int64_t looks most convenient for this purpose. Indefinite wait can be useful for simple apps when there are some external mechanism to stop flush if it has stalled - hardclose connection or maybe even kill process. Anyway, I think that currently passing max int64_t does not violates any specified api rules but does not work as expected.
