### ISSUE TITLE
stanConnection_Connect timeout when using with libuv

### ISSUE THREAD

**Issue by loint** [nats-io/nats.c#357]
Hi @kozlovic 

When I used stan and nats or nats with libuv as your example. They're working well.
But I'm trying to use Nat Streaming with libuv then stanConnection_Connect is always timeout.
I'm not sure why. I put these lines in a child thread.

```
natsLibuv_Init();
auto uvLoop = (uv_loop_t*) malloc(sizeof(uv_loop_t));
uv_loop_init(uvLoop);
natsLibuv_SetThreadLocalLoop(uvLoop);
natsOptions_SetEventLoop(
            natsOpts,
            (void*) uvLoop,
            natsLibuv_Attach,
            natsLibuv_Read,
            natsLibuv_Write,
            natsLibuv_Detach);

stanConnOptions_Create(&connOpts);
stanConnOptions_SetNATSOptions(connOpts, natsOpts);
natsOptions_Destroy(natsOpts);
s = stanConnection_Connect(&streamConnection, "test-cluster", "my-app", connOpts);
// Timeout ???
stanConnOptions_Destroy(connOpts);
```
Thank you very much

**Comment by kozlovic** [comment]
@loint Unfortunately you cannot use libuv/libevent or any other event loop with NATS Streaming because internally we coded the streaming library with use of request/replies. Most interactions with the streaming server is through request/reply. For instance, the `Connect()` is sending a request for a connection and waits for the reply.
This [link](https://github.com/nats-io/nats.c#using-an-event-loop-library) in the README touches on the reason why you cannot use request/reply APIs with an event-loop library.

**Comment by loint** [comment]
Ah ok, I see so it will not create many threads to subscribe, just pull messages as many other streaming broker does.
Thank you very much for your confirm @kozlovic

**Comment by kozlovic** [comment]
> Ah ok, I see so it will not create many threads to subscribe, just pull messages as many other streaming broker does.

Not sure what you mean here. The problem when using an external event loop library is that you cannot have the event-loop invoke a user callback (in this case, the NATS C library) that will block waiting for some I/O events.
If NATS C client library "sends" a connection request but in the same call blocks waiting for the reply, it will always timeout because the event loop is not given a chance to read from the socket and trigger registered callbacks for read events.
For that to work it would have needed a complete asynchronous development of the streaming library: that is, send the request, but return and wait for the event-loop to invoke it back with the reply, etc..
There is no plan to change the model at this point.
