### ISSUE TITLE
Question about natsSubscription_Drain

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#383]
Hello. I use natsSubscription_Drain instead of natsSubscribption_Unsubscribe everywhere because it provides stronger guarantees that message dispatched to the subscription on the server-side will not be lost.

I wish I can use this function in the following way:
1) call natsSubscription_Drain - documentation states that it performs asynchonously
2) Wait for subscription closed callback to be called (set with natsSubscription_SetOnCompleteCB)
3) Call natsSubscription_WaitForDrainCompletion inside onCompleteCB using zero timeout to obtain information whether subscription was drained or not,

Can you please tell me, whether 3 wil work? Will natsSubscription_WaitForDrainCompletion return the correct value? Will it return immediately or block for some time? I do not want to call natsSubscription_WaitForDrainCompletion on a separate thread to avoid blocking...

Also I've found some strange behaviour in my tests:
1) Client opens connection to the server, creates subscription, receives some messages on it and then the server is stopped
2) Client is configured to reconnect indefinetely, so it starts reconnecting after it detects connection loss (onDisconnectedCB is called)
3) natsSubscription_Drain is called for subscription created in 1 and freezes for a pretty big amount of time (10 seconds in my test) and then returns NATS_TIMEOUT (code 26). Subscription closed CB is not called.

Note, that documenation states that this function is not blocking and I think 10 seconds is a pretty big value for non-blocking. Maybe a better solution will be to immediately return error when disconnected? Is there any sense at all to try to perform subscription drain when connection is lost? I mean, I thought that drain is needed to receive all messages buffered on the server-side - but the connection is lost, and susbcription is already removed on the server (if I understand correctly).

**Comment by kozlovic** [comment]
> call natsSubscription_Drain - documentation states that it performs asynchonously

Well, it is a bit wrong since the connection is flushed to ensure that the unsubscribe protocol has been processed by the server. So this is a request/reply with the server and therefore can "block".

> Call natsSubscription_WaitForDrainCompletion inside onCompleteCB using zero timeout to obtain information whether subscription was drained or not,

First, value 0 (or negative) as indicated in the doc means to wait for ever. But if you invoke from the completion callback it means the subscription is done. So this call will return immediately either with a `NATS_ILLEGAL_STATE` saying that the subscription is/was not in draining mode, or NATS_OK otherwise.

> natsSubscription_Drain is called for subscription created in 1 and freezes for a pretty big amount of time (10 seconds in my test) and then returns NATS_TIMEOUT (code 26). 

That is the Flush I was referring to. The new default is 10 seconds (used to be 60s!). 

> Subscription closed CB is not called.

Yes, since the flush failed, the actual drain of the subscription did not happen.

> Is there any sense at all to try to perform subscription drain when connection is lost?

Agreed, if the connection is currently connected, the flush should fail immediately. I need to look into that.

> I mean, I thought that drain is needed to receive all messages buffered on the server-side - but the connection is lost, and subscription is already removed on the server (if I understand correctly).

No, the drain purpose is to send an unsubscribe protocol to the server, ensure that it is processed by the server (send a PING and processes the response PONG) and that tells the library that it now has the guarantee that no new message is going to come through, it can then switch the state to the subscription to "drain mode" to make sure that all messages are processed. But if you got disconnected say before the drain, as explained above, the drain will fail (due to the flush - but should fail right away if already disconnected) and the subscription won't be drained. But here is the problem, the library cannot switch to drain mode because it would then be possible that while draining the subscription, new messages arrive once connection is reconnected.
We *could* in situations where the flush fail, remove the subscription from the connection's list which would prevent any new message to be moved from connection to subscription, but still switch the subscription to drain mode so that all internal pending messages are processed.

I will look at why flush does not fail when disconnected, I think it should be the expected behavior. Also, will check if we can do what I described about some failure cases during the drain.

**Comment by kozlovic** [comment]
> Agreed, if the connection is currently connected, the flush should fail immediately. I need to look into that.

Actually, I take that back. If a flush is inflight (meaning the PING was sent and then the connection breaks) it gets kick out, which makes sense. However, if a Flush() is done while disconnected, it should not fail. Why? Because if you allow for a reconnect, then any protocol (PUB, SUB, UNSUB) is added to the pending buffer that will then be sent on reconnect. A Flush() allows you still to guarantee that anything before the Flush() call has been processed by the server. So it could be that you call Flush() and reconnection happens during the flush, and the flush would succeed. So we can't fail this Flush(). 

The main issue is probably that the Flush() in drain functions should be asynchronous, which we don't have provision for at the moment in the library. This would need to be fixed first.

**Comment by pananton** [comment]
Thank for your answers, @kozlovic !
Some more questions/suggestions )

> No, the drain purpose is to send an unsubscribe protocol to the server, ensure that it is processed by the server (send a PING and processes the response PONG) and that tells the library that it now has the guarantee that no new message is going to come through, it can then switch the state to the subscription to "drain mode" to make sure that all messages are processed.

Sorry, I was not attentive and thought earlier that natsSubscription_Unsubscribe also processes all messages queued in incoming buffer. But if I understand you correctly it does not - natsSubscription_Drain does. So if I have 100 messages in incoming buffer and call natsSubscription_Unsubscribe then I probably will lost some of them (or all) depending on race conditions. And if I use natsSubscription_Drain all will be processed (unless drain fails). Is that correct?

Now about suggestions:
1) It will be great if you will make natsSubscription_Drain completely async. Currently my own code can suffer long unexpected delays and it's an ugly solution to make subscription draining async using for example separate thread for each subscription drain operation. This solution I've already used for natsConnection_DrainTimeout - but this operation is relatively rare and it's ok to move it to separate thread.
2) Can you also add a function which can be used to determine whether subscription was successfully drained or not in subscription close cb? The purpose of my previous questions about natsSubscription_WaitForDrainCompletion was to figure out whether this function can be used in subscription close cb to just retreive the drain result of already closed subscription (but you said that this will not work). Btw, maybe I can get subscription statistics in subscription close cb and if it indicates that some messages are pending make assumption that drain has failed?
3) Allow to specify timeout in natsSubscription_Drain in a similar way used for natsConnection_DrainTimeout. The only way to set a timeout for subscription drain is to use natsSubscription_WaitForDrainCompletion - which I do not want to use at all because it blocks.

**Comment by kozlovic** [comment]
> Sorry, I was not attentive and thought earlier that natsSubscription_Unsubscribe also processes all messages queued in incoming buffer. But if I understand you correctly it does not - natsSubscription_Drain does. 

Correct. If the subscription has say some messages waiting to be dispatched and is currently in the user's message callback and natsSubscriptions_Unsubscribe() is invoked (either from the callback itself, or another thread), then the subscription will stop after the message callback returns. So there will be messages that will not be processed.

> And if I use natsSubscription_Drain all will be processed (unless drain fails). Is that correct?

Correct. Drain will send an UNSUBSCRIBE + PING protocols and when receiving the corresponding PONG will set the subscription in drain mode. In that case, the dispatcher loop will finish with all pending messages. When the loop ends, the subscription is removed from the connection.
If drain fails, say because of the flush, then the subscription is not drained nor closed. So with current code, if call to natsSubscription_Drain() returns NATS_OK, then the subscription will be properly drained. If it returns an error, it won't, unless the error is NATS_DRAINING, which means that the connection was already draining.

> It will be great if you will make natsSubscription_Drain completely async.

I will try, but we have no way as of now to have flush (PING/PONG) being handled asynchronously in the library, so would have to build that.

> Can you also add a function which can be used to determine whether subscription was successfully drained or not in subscription close cb

I don't think we need that. Since you use the completion callback, you will know when the subscription is done. To know if the subscription was drained or not, you CAN call natsSubscription_WaitForDrainCompletion(). This call will return NATS_ILLEGAL_STATE if the subscription was not switched to draining mode, and since also the subscription is closed at this point, this call will return immediately with NATS_OK if drained was invoked.

> Allow to specify timeout in natsSubscription_Drain in a similar way used for natsConnection_DrainTimeout.

Probably. But if we make the subscription drain completely async, then it is less of an issue. We still ideally want the unsubscribe protocol to be sent and receive the reply before switching to draining mode. What I am thinking, but there may be issues there that I will discover when trying to implement all this, is that if the flush fails, then I will remove the subscription from the connection (to prevent any new message to come in), but then will still switch to draining mode to finish with all messages that are pending. The issue with that is that natsSubscription_WaitForDrainCompletion() in the completion callback would not then be able to make the difference between a failure in the flush or not (since state would be draining). I could try to carry over the information about the failed flush.
I am not clear on what you would do with the information regarding successful drain (UNSUB + normal drain) versus partial (failed UNSUB but drain of pending).

**Comment by pananton** [comment]
> But if we make the subscription drain completely async, then it is less of an issue.

I think it's still an issue. Consider the situation when each incoming message requires a lot of time to process. If publisher is misbehaving for some reason then it is possible to have a lot of messages in incoming buffer when unsubscribe begins. And if we can't specify timeout for this operation then it can hang out processing..

> I am not clear on what you would do with the information regarding successful drain (UNSUB + normal drain) versus partial (failed UNSUB but drain of pending).

In fact I only need this for monitoring system health at least to some extent. To see whether there is a high probablility that some messages were lost or not. So for this purpose I think a better solution is to state that darin was successful only if everything (flush also) was done properly. But it's just my case, can't say for others.

Finally, I've also have a thing for you to consider regarding NATS requests. There is a small problem when sending requests on unstable connection. If request was sent but then publisher disconnects then I suppose a high probablity exists that after reconnect answer will not be received (because it was received on the server-side when publisher was away and was dropped as I suppose). Which means that request will be timed out and other system components waiting for it will stall for a request timeout value. I think that having an option to immediately finish requests with error in such case would be good. Note that while reconnecting requests still should be buffered and sent when connection established (as it at the moment) - I'm only telling about those request that were already sent but not answered when disconnect occurs. I can finish such requests on my own in the onDisconnected cb but in that case I will loose requests that were not sent yet at all (queued in the outgoing buffer) and which otherwise would succeed. I understand that implementing such option will be hard, so this is only for your consideration for future library versions.

Merry Christmas and a Happy New Year, thank you for your help)

**Comment by kozlovic** [comment]
> I think it's still an issue. Consider the situation when each incoming message requires a lot of time to process. If publisher is misbehaving for some reason then it is possible to have a lot of messages in incoming buffer when unsubscribe begins. And if we can't specify timeout for this operation then it can hang out processing..

Ok, so you would want still to be able to have the subscription being "forcibly closed", meaning that the dispatch loop stops after the user callback returns, if the drain timeout expires. Note that this is what is happening if the *connection* drain uses a timeout.

I wonder: if the UNSUB + flushing were failing, should the library still try to drain the pending messages or not? I was thinking it could, as long as the subscription is removed from the connection, the library could still try to process all pending messages? But I now realize that apparently one cannot "close" a subscription (call natsSubscription_Unsubscribe()) when it has been switched into drain mode. So that can be an issue..

> Finally I have one more question regarding subscription draining. If connection is permanently lost (for example, client is not configured to reconnect) will the messages in incoming buffer be processed or dropped? I suppose that they will be dropped - in that case is there any way to drain subscription in such situation?

They would be dropped. When connection is closed, all subscriptions are (forcibly) closed. So if a subscription is dispatching a message, as soon as that callback returns, the subscription will end the dispatch loop.

**Comment by kozlovic** [comment]
> But I now realize that apparently one cannot "close" a subscription (call natsSubscription_Unsubscribe()) when it has been switched into drain mode. So that can be an issue..

Yes, I think that this is an issue. I should be able to close the subscription at any time and make the drain stop. I need to look into that.

**Comment by pananton** [comment]
> Ok, so you would want still to be able to have the subscription being "forcibly closed", meaning that the dispatch loop stops after the user callback returns, if the drain timeout expires. Note that this is what is happening if the connection drain uses a timeout.

I think it will be great if connection draining and susbcription draining will be implemented in the same way.

> I wonder: if the UNSUB + flushing were failing, should the library still try to drain the pending messages or not?

I think that if natsSubscription_Drain is called and is not timed out yet then it must process messages from incoming buffer. Later if nats.c is not sure that everything was done correctly (which means that some messages can be lost, for example when unsub + flush has failed the probablity exists that server sent message to broken connection etc) it can signal that drain was not successful.

> Yes, I think that this is an issue. I should be able to close the subscription at any time and make the drain stop. I need to look into that.

That would be great. To tell the truth I was sure that this works the way you described and forget to write a test for such situation. Will wait for a PR) Thanks!

**Comment by kozlovic** [comment]
> I think it will be great if connection draining and subscription draining will be implemented in the same way.

So yes, if I provide a natsSubscription_DrainTimeout() and it takes longer to drain than the timeout, then it will forcibly close the subscription.

> I think that if natsSubscription_Drain is called and is not timed out yet then it always must process messages from incoming buffer.

Does that not contradict what you write just after?:

> for example when unsub + flush has failed the probability exists that server sent message to broken connection etc) it can signal that drain was not successful.

Are you saying that unless it is a "sub drain timeout", then the drain should still occur, but the user should be able to tell that the drain was possibly not complete?

I have a bit of an issue in trying to implement all that. The issue is that I document `natsSubscription_WaitForDrainCompletion()` this way:
```
This function blocks until the subscription is fully drained.
Returns no error if the subscription is drained or closed, otherwise
returns the error indicating why the wait returned before completion
or if the subscription was not in drained mode.
```
Note that I documented that it would return no error if the subscription is drained or closed.

I started to change that so that it would report NATS_INVALID_SUBSCRIPTION if the subscription has been closed before the drain complete. Not sure if this is ok since it was documented that it would not.
Also, I would need to be able to report possible other status (such as when the flush failed).

What do you think?

**Comment by pananton** [comment]
> Are you saying that unless it is a "sub drain timeout", then the drain should still occur, but the user should be able to tell that the drain was possibly not complete?

Sorry, probably misunderstood something again or was not clear enough. IMO drain success depends not only on whether incoming buffer was cleaned but also whether subscription was properly closed on the server-side (i.e. the situation when server thinks that subscription is working and sends messages to it while client already closed susbcription and discards this received messages is not possible).

Let me explain how I thought it works on the simple example. Suppose that there is 10 message in incoming buffer when connection is lost. Then while reconnecting client starts subscription drain:
1) unsub + flush are sent (actually buffered to reconnect buffer)
2) messages from incoming buffer continue to be passed to message callback *concurrently* (do not wait when unsub + flush are done)
3) connection is reconnected
4) unsub + flush sent
5) more messages can be already in incoming buffer, processing them too
6) success

Note that timeout can occur at any stage except 6: in that case drain is unsuccessful with timeout error. If unsub+flush are not delivered to server (1, 3, or 4 fails) then it's also an error but it should not affect processing of already received messages (unless timeout has elapsed). Which means that all 10 messages will be processed but the drain result will be set to an error.
I mean that phylosophy behind subscription drain should be to make it's best to finish gracefully but to finish with error if anything went wrong (but do not stop message processin on error).

**Comment by pananton** [comment]
> I started to change that so that it would report NATS_INVALID_SUBSCRIPTION if the subscription has been closed before the drain complete. Not sure if this is ok since it was documented that it would not.
Also, I would need to be able to report possible other status (such as when the flush failed). What do you think?

It's hard to say.. It breakes compatability, but in a place which is not very heavily used.. Maybe you need to increment major version. Or you can provide some new function for this purpose. Don't know which is better.

**Comment by pananton** [comment]
Looked into PR and it's great, thanks! I'd like to suggest one more modification to subscription draining. It requires modifications on the server-side too and is pretty hard to implement as I suppose. But maybe you will add this feature to your future roadmap.

Let me provide you a small information about our NATS usage experience. We use NATS as a backend for our microservices. We do not use NATS streaming for most of operations because it incurs additional performance penalties and it's ok to loose small number of messages from time to time for us. We also try to deliver new features as fast as possible and expect that microservices will be restarted often as part of our CI/CD pipeline. To provide stronger delivery guarantees during restarts we launch at least 2 microservice instances and restart them gracefully (one after another) with connection/subscription draining.

Currently there exists one problem when susbcription is closing. Even if everything was ok during unsubscribe I suppose that messages still can be lost. Simple example (note that I'm not sure whether I understand correctly the server internals, maybe the problem I'm worrying about does not exist at all):
1) we have 2 node cluster A and B
2) publisher is connected to A
3) 2 susbcribers S1 and S2 are connected to A and B correspondingly and are joined into the same queue group
4) S2 (connected to B) closes it's subscription, unsub protocol message is parsed by B (susbcription is remove on B node) and forwarded to A
5) A receives message from the publisher and because it has not received unsub from B yet it can choose susbcriber on B and sent message to it
6) node B receives forwarded message but because its subscription is already removed, simply discards it

I'd like to ask you to consider modification to unsubscribe operation that will provide strong guarantees that if no disconnects (between client and server or between server nodes) occur while unsubscribing then published messages can't be lost. This will probably require to modify unsub protocol message to await all cluster nodes to process it and only after that return some operation result to client. The implementation becomes even harder (maybe impossible) if we consider nats supercluster topology. But probably at least for the nodes of the same cluster this can be done.

**Comment by kozlovic** [comment]
@pananton The servers are actually already doing that: in step 6, when server B receives a message from A for a queue subscriber, but then realize that there is no member left, it will send it back to A. Server A will then pick a local queue subscriber to redeliver the message to. So for this issue, we are covered already.

**Comment by pananton** [comment]
That's great, thank you!
