### ISSUE TITLE
Event loop and async delivery

### ISSUE THREAD

**Issue by vedmysh** [nats-io/nats.c#396]
Hello.
Merely a question than issue. Working on integration libev with nats.c and noticed, that even in case of event loop usage we still have a separate thread (or thread from pool) for async delivery (sub.c, natsSub_create()). Any chance this will be changed in future (or maybe will be as an option) so we are able to handle onMsg callback on the same thread where event loop is runnning?
ps Happy new year in advance :)

**Comment by kozlovic** [comment]
@vedmysh There is currently no plan to have subscriptions' callbacks invoked directly from the connection read loop or in this case from the event loop.

Have you experimented with synchronous subscriptions? There is no thread created for that kind of subscription. Of course in that case you would be responsible for invoking natsSubscription_NextMsg() (with a timeout of 0, which will not block if there is no pending message and return NATS_TIMEOUT), and it means you would be running the event loop in a mode where you have the chance to run your code as opposed to all be driven by callbacks.

We have so far be "against" running user callbacks from the connection's read loop because of the risk of slowing down to the point that the server would close the connection as slow consumer. I would also prevent any use of request/flush calls since they would by nature "deadlock".

Happy New Year to you too!
