### ISSUE TITLE
Parsing URL fails with "invalid port" error if there is a path after the port

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats.c#417]
For instance, using this URL: `nats://localhost:4222/subject` will fail since v2.4.0 but was working before.
Note that NATS does not use anything after the port, but still, there is no reason to fail the parsing.

Reported by @RudeDude and @counterflow-ai.

**Comment by RudeDude** [comment]
Thanks for creating and tracking this issue @kozlovic !

Getting message during connect/setup:
> error: (util.c:112): invalid port '4222/subject'

file src/url.c around line 40 has perhaps changed the behavior. You used to parse an int directly atoi() from the pointer to a string position (in my case :4222/subject ). Now you call ParsePort which is in util.c line 110 ( parseInt64() is called instead of atoi() )

**Comment by kozlovic** [comment]
PR coming shortly...

**Comment by kozlovic** [comment]
@RudeDude Ok, PR #418 is up. If you want to have a look there and/or test it, that would be appreciated.

**Comment by RudeDude** [comment]
Fix confirmed!
I checked out v2.4.0 and did a `git merge fix_417`, build etc and it works great!
