### ISSUE TITLE
Add support for new "no responders" error code for natsConnection_PublishRequest

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#421]
Hello!
I'm using natsConnection_PublishRequest to publish requests and later parse replies in my own inbox subscription (which is passed in 'reply' function parameter). If there is no responder for the request (I'm using nats-server v2.2.5) then in my inbox I receive a reply for which natsMsg_GetDataLength returns 0 (so it is treated as empty message).
Can you please add some way to figure out that there were no responders for request for my use-case? Need it very much because natsConnection_Request which supports NATS_NO_RESPONDERS does not suite me at all due to it's sync nature.

Possible solutions:

Store natsStatus error code in natsMsg and:

1 - add a `natsStatus*` [out] parameter for natsMsg_GetReply to signal NATS_NO_RESPONDERS for replies
2 - add a function natsMsg_GetError which returns error code for a message

**Comment by kozlovic** [comment]
> Can you please add some way to figure out that there were no responders for request for my use-case?

Technically, there already is, but you would have to know the key and value of the header to check.

When using `natsConnection_PublishRequest()` (and its variants), the subscriptions (async or sync) on the reply subject will indeed receive an empty message with a header indicating that this is a "no responders" message.
At the very least I think I need to fix `natsSubscription_NextMsg()` to return `NATS_NO_RESPONDERS` when detecting this situation. It may break some applications, but I already warned about the change in nats.c v2.2.0 when introducing the feature, saying that natsConnection_Request() would return a different error code. 
For background: I disagreed to make the "no responders" feature not be an opt-in since it could break users applications (see https://github.com/nats-io/nats.c/pull/353#discussion_r461887292 for details).

For async subscriptions, I could:
- filter out the "no responders" messages so that callback would never see this empty message, but at the same time would not know that there was no response
- pass the empty message to the callback, but have a new API, say `natsMsg_IsNoResponders(m *natsMsg)` to know if this is a "no responders" message, but then it means that one would have to call that at the beginning of all message callbacks, well, at least for all message callbacks that are setup on a subject that is used as the reply subject.

Which approach would you think is best? (at least for you, that may not be what other wants)
Regardless the approach, we could add connection's option to change the behavior, but would need to agree on what is the best default behavior.

**Comment by kozlovic** [comment]
Check this function: https://github.com/nats-io/nats.c/blob/45116189ff216da52472fbe171e03a01db23cb62/src/pub.c#L328

The header is "Status" and value to check for no responders is the string "503".

Yes, I think the second approach may actually be better. The new API would be a convenient method so one does not have to explicitly check the header, etc..

**Comment by pananton** [comment]
Thank you! Will try.
