### ISSUE TITLE
asynchronous subscription & concurrent

### ISSUE THREAD

**Issue by acsdkquery** [nats-io/nats.c#441]
Have created 100 connections in a queue group as a asynchronous subscription in the **single** process

#define MAX_NATS_CONN 100
static natsConnection      *conn[MAX_NATS_CONN] = {0};
int main(int argc, char **argv){
            for (int c =0; c < MAX_NATS_CONN ; c++) {
              natsConnection_Connect(&conn[c], opts);
              natsConnection_QueueSubscribe(&sub, conn[c], subj, name, onMsg, NULL);}
}

notes from readme:
When you create an asynchronous subscription, the library will create a thread that is responsible to dispatch messages for that subscription. messages from a given subscription are always dispatched sequentially and from the **same** thread

Question:
Suppose if I publish 200 messages and consider messages are equally distributed among 100 connections,
i.e, 1 connection has 2 max pending messages

whether it can able to process 100 messages concurrently?
whether 'onMsg' will be concurrently called and processed, if all connection has a message to process at the same time?
(Note: this is on a single process)

**Comment by kozlovic** [comment]
This is correct. Since you have multiple subscriptions, each subscription may be able to dispatch (that is call the message callback) concurrently. What the README says is that for a *given* subscription, pending messages are dispatched one at a time.

So in your case, you could have possibly 100 `onMsg` callback executing at the same time, which means it is then important that the code in your message callback is thread safe.
