### ISSUE TITLE
JetStream 

### ISSUE THREAD

**Issue by mtcunningh** [nats-io/nats.c#455]
Does the C client library actually work with JetStream? I'm using nats server 2.3.4 (started with -js option) and the nats.c 3.0.0 library. I can not get this to work. The call to ```js_Subscribe``` always fails. See code below.

```
#include <string>
#include <iostream>
#include "nats/nats.h"

static void
onStreamMsg(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure)
{
        printf("Received msg: %s - %.*s\n",
               natsMsg_GetSubject(msg),
               natsMsg_GetDataLength(msg),
               natsMsg_GetData(msg));


    natsMsg_Ack(msg, NULL);
    natsMsg_Destroy(msg);
}

int main(int argc, char **argv)
{
   natsConnection      *conn = NULL;
   natsStatus          s;
   natsOptions* str_opts; 

   natsOptions_Create( &str_opts );
   natsOptions_SetURL(str_opts, NATS_DEFAULT_URL);

   s = natsConnection_Connect(&conn, str_opts);

   if (s == NATS_OK)
   {
      std::cout << "connected to nats regular" << std::endl;
   }
   else
   {
      std::cout << "not connected to nats regular" << std::endl;
   }

   // Initialize and set some JetStream options
   jsOptions jsOpts;
   jsCtx* js = NULL;

   jsOptions_Init(&jsOpts);

   s = natsConnection_JetStream(&js, conn, &jsOpts);
   if (s == NATS_OK)
   {
      std::cout << "connected to js" << std::endl;
   }
   else
   {
      std::cout << "not connected to js" << std::endl;
   }

   natsSubscription    *sub  = NULL;
   jsSubOptions        so;
   jsSubOptions_Init(&so);
   jsErrCode           jerr;

   s = js_Subscribe(&sub, js, "foos", onStreamMsg, NULL, &jsOpts, &so, &jerr);
   if (s == NATS_OK)
   {
      std::cout << "js subscribe ok" << std::endl;
   }
   else
   {
      std::cout << "js subscribe not ok: " << jerr << std::endl;
   }

   std::string msg1("dg");
   std::string msg2("th");
   std::string msg3("cs");

   js_PublishAsync(js, "foos", (const void*) msg1.c_str(), sizeof(msg1.c_str()), NULL);
   js_PublishAsync(js, "foos", (const void*) msg2.c_str(), sizeof(msg2.c_str()), NULL);
   js_PublishAsync(js, "foos", (const void*) msg3.c_str(), sizeof(msg3.c_str()), NULL);

   std::cin.get();

   natsConnection_Destroy(conn);

   return 0;
}
```

**Comment by kozlovic** [comment]
Few notes, you don't need to declare `jsOptions` and `jsSubOptions` and initialize them if you are not setting anything special. You can pass `NULL` for those.

Would be great if you had posted the error returned (you can use `nats_PrintLastErrorStack(stderr);` that may also give more info.

Do you have a stream created somewhere? I don't see the code creating it here, so it has to be created somewhere else. The stream you want to use needs to be configured so that it stores messages on this subject "foos" that you use here. I would recommend that you check the JetStream documentation: https://docs.nats.io/jetstream/jetstream.

If the stream indeed already exists, make sure to either specify its name through the `jsOpts.Stream` option, or make sure that the library is able to find a matching stream based on the subject provided (here "foos"). It is possible only if there is a single stream that filters on this subject.

**Comment by kozlovic** [comment]
@mtcunningh Since you did not send any update, I assume that the issue was resolved. I am closing this issue for now.
