### ISSUE TITLE
Issues with JetStream Examples

### ISSUE THREAD

**Issue by swDevTX** [nats-io/nats.c#544]
I'm trying to learn NATS.io JetStream using the nats.c libraries.  I looked in the example directory provided and reviewed "js-sub.c" and "js-pub.c".  I'm trying to run these example tools and seeing inconsistent behavior.  

1) If I run `nats-js-pub -stream "foo" -count 1000`, it publishes 1000 messages and then promptly deletes stream "foo".  Subsequently running `nats-js-sub -stream "foo"` leaves no messages to be read.  Ok, fair enough, I'll reverse the order and run `nats-js-sub -stream "foo"` first and then run `nats-js-pub -stream "foo" -count 1000`.  Nope, basically the sub just sits there waiting on messages forever.  (_Note: if I don't enter `-count 1000` and let the default million messages go, I can get it to work.  Pretty much the only way I've gotten it to work is when sending the million messages. It also works if I put `-count 1000000`.  Seems odd_)

2) Likewise, if I run `nats-js-sub -stream "foo" -sync` and `nats-js-pub -stream "foo" -sync -count 1000`, I get nothing.  Basically, it just seems like it doesn't work at all.  As with running async, if I do not put the `-count`, I can get it to work.

Is there some number of bytes that must be pushed by the publisher for the subscriber to actually receive data here?  I also gave a "-count 2000000" a go and that didn't work either.  In the cases, I've tried other than one million, the publisher always seems to publish the messages OK.  But the subscriber will sit there stuck.  Subsequent runs of the subscriber will note that the correct number of messages are on the stream, but again sit there seemingly stuck. 

I'm running nats.c v3.2.0 with NATS server 2.8.2.  Currently, I'm just running `nats-server -js`.  I was just getting started so I haven't done any additional server configuration. (Maybe that's my issue?)  For now, I'm simply running everything on RHEL 7.8

**Comment by kozlovic** [comment]
@swDevTX The tools use a default message count of 1,000,000. When you run the publisher with less messages, the subscriber tool will seem to just sit waiting, because that is what it is doing: waiting for the default 1,000,000 messages to arrive. So if you change the number for the publisher, then change it for the subscriber too.

As you have seen too, since the pub and sub report performance at the end of the run (very simplistic benchmark tool), the messages are not printed by default. If you pass the `-print` option on the command line, then you should see that the subscription tool did in fact receive some messages, just not all of them.
