### ISSUE TITLE
jsErrCode comments/naming incorrect in status.h?

### ISSUE THREAD

**Issue by swDevTX** [nats-io/nats.c#572]
If I create a new stream with overlapping subjects, I get error code 10049 which in status.h is commented as "Generic stream creation error".  That error wasn't particularly helpful.  Once, I figured out what I actually did using the NATs CLI tool, I saw the same error code 10049 with the text that read "nats: error: could not create Stream: subjects overlap with an existing stream (10049)"

A quick search in status.h for "subjects overlap" has this mapping:

`JSStreamSubjectOverlapErr = 10065`

Seems like maybe JSStreamSubjectOverlapErr should be set to 10049.   And, if so, are there others?

**Comment by kozlovic** [comment]
Note that the server sends those code, the client library just present it to the user. I see a difference in standalone server and cluster where in cluster mode the server will return the expected 10065, while in standalone the server sends a non JS error which then causes it to send a generic 10049 with the description: https://github.com/nats-io/nats-server/blob/76219f8e5b87efb639f7c7e1de6af32af61a562c/server/stream.go#L405.

I will file an issue in nats-server and have a fix for the next v2.9.0 release. Closing this issue now since the client does the right thing of reporting the error returned by the server.
