### ISSUE TITLE
Please document the use of UTF-8

### ISSUE THREAD

**Issue by Kazmirchuk** [nats-io/nats.c#573]
Hi,

neither the nats.c docs, nor nats-server docs mention, if I can use Unicode.

All C API accepts char* that might work with UTF-8 (and usually it does e.g. in POSIX API). I did notice that you use const void * for messages payload and values in KV store.

I'd be happy to have an official confirmation that I can (or must not) use UTF-8 in:
- subjects
- names of consumers and streams
- password in CONNECT
- message headers in HPUB (keys & values)
- keys in KV store

etc

The reason for asking is that I'm writing a C++ wrapper over nats.c and in my framework (Qt) Unicode is mainly stored as UTF-16, so I need to call correct conversion functions. If only Latin-1 is allowed, then I'll stick to it.

Thanks in advance

**Comment by Kazmirchuk** [comment]
ok I've found some clarification from Derek but it dates back to 2019, and it's only about subjects

https://github.com/nats-io/nats-server/issues/711

**Comment by kozlovic** [comment]
@Kazmirchuk You should stick to ASCII for all that is subjects, stream/consumer names, keys in KV store (since they are subject), password in CONNECT (since I am doing a snprintf there, not a full JSON encoding).

The payload of messages is a byte array, NATS (both server and client) don't care about the content, it is responsibility to applications to encode/decode appropriately.
