### ISSUE TITLE
natsConnection_Status segfaults

### ISSUE THREAD

**Issue by dor132** [nats-io/nats.c#606]
Hi.
This may be expected behavior and a programmer mistake, however I came across this today.
When calling `natsConnection_Status` with a `natsConnection` argument that had been destroyed using `natsConnection_Destroy`, the function segfaults.
The cause for this is probably an uninitialized `pthread` mutex in the `natsConnection` delivered to the function.
Is this intentional?

Code to reproduce:
```cpp
#include <iostream>
#include <nats/nats.h>

int main() {
  natsConnection* nc = nullptr;
  natsConnection_ConnectTo(&nc, {"127.0.0.1:4222"});

  natsConnStatus cs = natsConnection_Status(nc);
  if (cs == natsConnStatus::NATS_CONN_STATUS_CONNECTED) {
    std::cout << "Connected to NATS\n";
  }
  
  natsConnection_Destroy(nc);

  cs = natsConnection_Status(nc); // SEGFAULTS
  if (cs == natsConnStatus::NATS_CONN_STATUS_CONNECTED) {
    std::cout << "Disconnected from NATS\n";
  }
}
```

**Comment by kozlovic** [comment]
@dor132 This is "expected" since `natsConnection_Destroy()` will free memory. It would be equivalent of allocating a pointer in C, then freeing it, then trying to reference this pointer.

If you were to replace `natsConnection_Destroy()` with `natsConnection_Close()`, then the connection pointer is still valid (until you call `natsConnection_Destroy()`). By the way, the last check should then be `NATS_CONN_STATUS_CLOSED` since you closed the connection. It could be `NATS_CONN_STATUS_DISCONNECTED` if the server was stopped, instead, etc....
