### ISSUE TITLE
Jetstream consumer configuration

### ISSUE THREAD

**Issue by daniiarov-alym** [nats-io/nats.c#618]
This, of course, might be just me being an idiot, but I have a several questions on consumer configuration. 

So in my app I want to create consumer if one does not exist already and then assign subscriptions to it. As far as I understood this is done via

```c++
natsStatus s = js_GetConsumerInfo(&consumer_info, ctx, stream.c_str(), consumer.c_str(), &js_options, nullptr);
// part of code ommited 
jsConsumerConfig cfg;
jsConsumerConfig_Init(&cfg);
cfg.Durable = consumer.c_str();
cfg.DeliverSubject = stream.c_str();
s = js_AddConsumer(&consumer_info, ctx, stream.c_str(), &cfg, &js_options, nullptr);
```

and then further
```c++
jsSubOptions sub_options;
natsStatus sub_status = jsSubOptions_Init(&sub_options);
// omited part of code
sub_options.Stream = stream.c_str();
sub_options.Consumer = consumer.c_str();
sub_options.Queue = nullptr;
sub_options.ManualAck = false;
sub_options.Ordered = false;
jsConsumerConfig_Init(&sub_options.Config);
jsErrCode  jerr = static_cast<jsErrCode>(0);
natsSubscription* sub = nullptr;
	
for (auto i = 0; i < subjects.size(); ++i)
{
	sub_status = js_Subscribe(&sub, ctx, subjects[i].c_str(), message_cb, (void*)msg_handler, &js_options, &sub_options, &jerr);
}
```

Apparently this is not best piece of code, but still couple of issues coming in here from me:
First of all if I do 
```sub_options.Ordered = true;```
then it is going to fail to
```c
// Check for bound consumers.
        if (!nats_IsStringEmpty(consumer))
            return nats_setError(NATS_INVALID_ARG, "%s", jsErrOrderedConsNoBind);
```
error. 
Secondly, if I do not specify 
```
cfg.DeliverSubject = stream.c_str();
```
by any subject then I am not able to create any subscription due to 
```c
// Prevent binding a subscription against incompatible consumer types.
    if (isPullMode && !dlvSubjEmpty)
    {
        return nats_setError(NATS_ERR, "%s", jsErrPullSubscribeToPushConsumer);
    }
```

is that behaviour valid? Or am I misunderstanding something fundamentally?

**Comment by kozlovic** [comment]
@daniiarov-alym There are several issues in the way you are doing things indeed. First, see JS consumers as "view" of a stream. If you get the consumer info, and that is successful, then there is no need to call AddConsumer, since the consumer already exists. 

Note that you don't need to change the deliver subject any time you start your application. You could reuse the one that was specified when creating the JS consumer the first time. 

As for the code prior to call `js_Subscribe()`, `jsSubOptions_Init()` is initializing the subscription options structure, including internal jsConsumerConfig, so you don't need to call  jsConsumerConfig_Init() there. You also don't need to set some of the fields to their "default" non set values, such as boolean to `false` or pointers to `NULL`.

The reasons you get the errors you get is because options provided to `js_Subscribe()` need to "match" the JS consumer that was created (either with `js_AddConsumer()` or externally with the NATS CLI), so you can't for instance specify a deliver subject for an existing JS consumer if one was created without (which makes it a pull consumer).

For the "ordered" flag, you can't set this and bind to an existing consumer (when stream and/or consumer name are specified in the options when calling `js_Subscribe()`.

Finally, I am not sure why you repeat the call `js_Subscribe()` for several subjects. This is not how this works. If you have a stream that collects several subjects (for instance due to use of wildcards), when you create the JS consumer you can get all subjects with a single `js_Subscribe()` call, or otherwise if you want just a subset you need to create the JS consumer with a `FilterSubject`).

I would strongly recommend that you have a look at the JetStream documentation [here](https://docs.nats.io/nats-concepts/jetstream), and specifically for consumers [here](https://docs.nats.io/nats-concepts/jetstream/consumers).
