### ISSUE TITLE
Rate Limit of Push Consumers for KV Watches

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.c#619]
Is it possible to apply RateLimit using nats-c to the underlying push consumer when watching a KV ?

Users would like to throttle the initial reply when watching all.

**Comment by derekcollison** [comment]
It does not, but the ordered consumers flip out ephemerals as normal course when data is missed, so we could use same trick to switch over after initial messages received.

**Comment by derekcollison** [comment]
The watchers for the KV should be flow controlled, so before going down the path of rate limits, which can be useful but usually are the wrong solution to a problem, I would like to understand a few things.

1. Were you using the KV watchers?
2. Will check with @kozlovic but they should be flow controlled.
3. What problems were you seeing on the network in your setup.

**Comment by kino71** [comment]
hello @derekcollison, 
we are using KV watchers, our process does a "watchall" upon startup and keep watching for key updates (key updates aren't frequent).
With 5 process running on a single host, when restarted simultaneously,  we see a number of "slow consumers" events, reconnection so on, due to the host's network being overwhelmed. Everything is handled well by nats and nats.c library.
Our process run in production as a single instance on over 50 dedicated host. Our concern was about overwhelm Nats network if restarted all at once (it happens after a network failure for instance). 
We use to have a connection to a database and the "restart-all" scenario was a nightmare...

I'm not able to try the exact same scenario in dev/test but once in production I could run a few tests on weekends.

**Comment by ripienaar** [comment]
I use randomised sleeps at start for this kind of process and it works well to control the impact of a cold start. Success with thousands of subscribers. 

If you have 5 processes each doing this on one node probably flow control won’t help much but rate limit might. You could also consider 1 process that manages a local cache of the data - so your other processes just reads, for example, a local JSON file and watch it for changes. Thus you get 1/5th of the traffic. 

Cold start that’s a thundering herd will always be problematic so the real solution isn’t to find a more thundering herd resistant tech but to control the real problem instead

**Comment by kino71** [comment]
Randomized sleep is a good idea, we currently restart this way during controlled startup (daily, very early in the morning).
We might add a random sleep when the restart is after a sudden crash.
In production we have a phyisical host per process, no way to share anything locally. We will containerize (docker) this application, in that case we'll be able to do as you suggest.
This week we'll give a try to this implementation (RateLimit option) and report back.
thanks!

**Comment by derekcollison** [comment]
You should not be seeing any slow consumers since the watchers should be flow controlled.

Can you give us more information on the slow consumers you are seeing?

**Comment by kino71** [comment]
Hi, I finally have had some time to run a few test.
You are right, we no longer see "slow consumer" errors. I think there were only before nats.c was patched (nats.c issue #600 #601 #602 ).

We'll see what happens in production when all our processes restart at the same time and then will decide whether to use RateLimit option.

thanks

**Comment by kozlovic** [comment]
@kino71 Hi, I was wondering if you had time to evaluate the PR. If there is no need, I would rather close and not merge it because we don't need to add features that are not proving beneficial.
