### ISSUE TITLE
Ordered sync JS subscription example

### ISSUE THREAD

**Issue by flaviup** [nats-io/nats.c#649]
Do you know if JetStream ordered sync subscriptions are working?
Something like below:

so.Ordered = true;
so.Stream = "MyStream";
so.Consumer = so.Ordered ? nullptr : "MyConsumer";
so.ManualAck =true;
so.Config.Name = "MyConsumer";
so.Config.Durable = so.Ordered ? nullptr : "MyConsumer";
so.Config.Description = "My consumer";
so.Config.AckPolicy = so.Ordered ? static_cast < jsAckPolicy > ( -1 ) : jsAckPolicy::js_AckExplicit;
so.Config.AckWait = 10 * 1'000'000LL;
so.Config.MemoryStorage = InMemory;
so.Config.ReplayPolicy = jsReplayPolicy::js_ReplayInstant;
so.Config.DeliverGroup = "MyConsumer";

auto s = js_SubscribeSync(&sub, _js, subj.data(), &_jsOpts, &so, &jerr);

When I try the above subscription I get the following error: ack policy can not be updated.

**Comment by kozlovic** [comment]
You create an ordered consumer on a stream, not on an existing consumer. The configuration should be very minimal, and you should not set any if the so.Config fields. Basically something like this:
```
jsSubOptions_Init(&so);
so.Ordered = true;
so.Stream = "MyStream";
s = js_SubscribeSync(&sub, _js, subj.data(), &_jsOpts, &so, &jerr);
```
The library will set some configuration settings such as memory storage, etc.. so that should really all there is to it. You can't use with queues, so again setting so.Config.DeliverGroup would not have worked.

**Comment by flaviup** [comment]
Thank you @kozlovic . It seems to be working with the sample code you provided.
What should be the jsRetentionPolicy of the streams for sync and async ordered subscriptions?

**Comment by kozlovic** [comment]
There is no specific retention policy for these type of consumers. You should use the stream retention policy that makes sense to you (and other types of consumers that you may use).
