### ISSUE TITLE
callback during nats reconnecting

### ISSUE THREAD

**Issue by mariahyang** [nats-io/nats.c#675]
looks we have callback `natsOptions_SetDisconnectedCB` after nats reconnected successfuly，but how set a callback during connecting?

**Comment by kozlovic** [comment]
We currently do not offer callbacks that track all events of the (re)connecting process. Also, something to keep in mind is that the way we execute those callbacks, it would not really work since those are invoked asynchronously, that is, when the user callback executes, the state of the connection may not be what the callback indicates (for instance the disconnected callback may execute while the connection is already reconnected (see warning [here](http://nats-io.github.io/nats.c/group__callbacks_group.html#gacdef6aff3e47953f19e35857ab8e274c)).

We would need to introduce a new set of callbacks (or an option that changes the behavior) to invoke callback "in place" for the feature you are asking makes sense. I don't believe there are plans at the moment for doing that.
